server:
  port: 8089

spring:
  datasource:
    name: smart_blog
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      mysql:
        #监控统计拦截的filters
        filters: stat
        driver-class-name: com.mysql.cj.jdbc.Driver
        #基本属性
        url: jdbc:mysql://127.0.0.1:3306/smart_blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        # 连接失败重试3次
        connection-error-retry-attempts: 3
        break-after-acquire-failure: true
      postgresql:
        #监控统计拦截的filters
        filters: stat
        driver-class-name: org.postgresql.Driver
        #基本属性
        url: jdbc:postgresql://127.0.0.1:5432/smart_blog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: postgres
        password: 123456
        #配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        #获取连接等待超时时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        #一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
          # 连接失败重试3次
          connection-error-retry-attempts: 3
          break-after-acquire-failure: true
  servlet:
    multipart:
      max-file-size: 10
      max-request-size: 100

  messages:
    basename: i18n/message
    encoding: utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.learn.blog.model
  configuration:
    map-underscore-to-camel-case: true


